CREATE SEQUENCE IF NOT EXISTS SQ_ACCOUNT_IDT;
CREATE SEQUENCE IF NOT EXISTS SQ_AGENCY_IDT;

CREATE TABLE IF NOT EXISTS ACCOUNT (
	IDT_ACCOUNT BIGINT DEFAULT SQ_ACCOUNT_IDT.NEXTVAL,
	COD_ACCOUNT VARCHAR(32) NOT NULL,
	COD_CUSTOMER VARCHAR(32) NOT NULL,
	DAT_CREATION TIMESTAMP NOT NULL,
	DAT_UPDATE TIMESTAMP,
	IND_STATUS VARCHAR(10) NOT NULL,
	NUM_NUMBER INT NOT NULL,
	IDT_AGENCY BIGINT NOT NULL,
	PRIMARY KEY (IDT_ACCOUNT)
);

CREATE UNIQUE INDEX IF NOT EXISTS ACCOUNT_UK01 ON ACCOUNT (COD_ACCOUNT);
CREATE UNIQUE INDEX IF NOT EXISTS ACCOUNT_UK02 ON ACCOUNT (COD_CUSTOMER);
CREATE UNIQUE INDEX IF NOT EXISTS ACCOUNT_UK03 ON ACCOUNT (IDT_AGENCY, NUM_NUMBER);

CREATE TABLE IF NOT EXISTS AGENCY (
	IDT_AGENCY BIGINT DEFAULT SQ_AGENCY_IDT.NEXTVAL,
	NUM_NUMBER INT NOT NULL,
	NUM_NEXT_ACCOUNT INT NOT NULL,
	DAT_CREATION TIMESTAMP NOT NULL,
	PRIMARY KEY (IDT_AGENCY)
);

CREATE UNIQUE INDEX IF NOT EXISTS AGENCY_UK01 ON AGENCY (NUM_NUMBER);

ALTER TABLE ACCOUNT ADD CONSTRAINT IF NOT EXISTS FK_AGENCY FOREIGN KEY (IDT_AGENCY) REFERENCES AGENCY(IDT_AGENCY);
