CREATE SEQUENCE IF NOT EXISTS SQ_ACCOUNT_BALANCE_IDT;

CREATE TABLE IF NOT EXISTS ACCOUNT_BALANCE (
	IDT_ACCOUNT_BALANCE BIGINT DEFAULT SQ_ACCOUNT_BALANCE_IDT.NEXTVAL,
   	COD_ACCOUNT VARCHAR(32) NOT NULL,
   	NUM_OPERATION_ORDER BIGINT NOT NULL,
   	NUM_BALANCE DOUBLE PRECISION NOT NULL,
   	FLG_BLOCKED BOOLEAN NOT NULL,
	DAT_UPDATE TIMESTAMP NOT NULL,
	PRIMARY KEY (IDT_ACCOUNT_BALANCE)
);

CREATE UNIQUE INDEX IF NOT EXISTS ACCOUNT_BALANCE_UK01 ON ACCOUNT_BALANCE (COD_ACCOUNT);

